name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  set_up_job:
    runs-on: ubuntu-18.04
    env:
      COMMIT_NOT_CONTAINS_SKIP_STRING: ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    steps:
      # - name: gihub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo $GITHUB_CONTEXT. GLobal env variablee $COMMIT_NOT_CONTAINS_SKIP_STRING
      # - name: commits
      #   env:
      #     COMMITS: ${{ toJson(github.event.commits) }}
      #   run: echo "$COMMITS"
      # - name: print env variable
        # env:
        #   COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        # if: ${{ github.event_name == 'push' && env.COMMIT_NOT_CONTAINS_SKIP_STRING }}
        # run: echo We use env variable $COMMIT_NOT_CONTAINS_SKIP_STRING
      - name: joined commit message
        env:
          CHECKED_JOINED_COMMIT_MESSAGE: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: echo "$CHECKED_JOINED_COMMIT_MESSAGE"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      # - name: build
      #   run: npm run build
      # - name: test
      #   run: npm run test
      # - name: e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
      #   if: ${{ github.event_name == 'push' && env.COMMIT_NOT_CONTAINS_SKIP_STRING }}
      # - uses: actions/checkout@v2
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.33.0
      #   if: ${{ github.event_name == 'push' && env.COMMIT_NOT_CONTAINS_SKIP_STRING }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: patch
      #     # DRY_RUN: true
      #     COMMIT_CONTAINS_SKIP_STRING: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
      # - name: heroku deploy
      #   uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      #   if: ${{ github.event_name == 'push' && env.COMMIT_NOT_CONTAINS_SKIP_STRING }}
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: pokedex-app-openstack #Must be unique in Heroku
      #     heroku_email: santiagobn1@gmail.com
      #     healthcheck: "https://pokedex-app-openstack.herokuapp.com/health"
      #     checkstring: "ok"
      #     rollbackonhealthcheckfailed: true
      - name: Sucess notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: took, commit
          custom_payload: |
            {
              attachments: [{
                "author_name": "8398a7@action-slack",
                "text": `A new version deployed to https://pokedex-app-openstack.herokuapp.com (${process.env.AS_COMMIT}) by ${process.env.COMMIT_AUTHOR} ${{ job.status }} build took ${process.env.AS_TOOK}`,
                "color": "good",
              }]
            }
          channel: "#notifications"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
          COMMIT_AUTHOR: ${{ github.event.commits[github.event.commits.length-1].author.name }}
        if: ${{ github.event_name == 'push' && job.status  == 'success' }}
      - name: Failure notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest 
          channel: "#notifications"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          COMMIT_AUTHOR: ${{ github.event.commits[github.event.commits.length-1].author.name }}
        if: ${{ job.status  == 'failure' }}